### ISSUE TITLE
Block context?

### ISSUE THREAD

**Issue by danialvz** [Log1x/acf-composer#130]
Hi! This might be a dumb question, but I wasn't able to find any info on this. Is there a way to define [block context](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-context/)  using the Block class definition?

Thanks

**Comment by Log1x** [comment]
I added the missing call for `$context` in the block render callback but I'm only seeing it return output like:

![Screenshot](https://i.imgur.com/fUuS0kf.png)

What were you trying to achieve exactly? Maybe you can pass a specific context using [`$supports`](https://github.com/Log1x/acf-composer/blob/master/src/Console/stubs/block.stub#L92) or something? Can you give me an example of a use-case for this so I can better understand? 

I'm thinking just needing `$context` available is not all that you needed.

**Comment by pat-flew** [comment]
Hey log1x, not sure if related, but I was looking for something that sounds a bit similar to OP

I need to supply `uses_context` value when registering a new block, so that when the block placed within a query loop, it can retrieve the queryId value created by the query loop block. It is ultimately for a query filter block that will be exposed to the user.

I've created a pull request for the update #153
