### ISSUE TITLE
Require fails, if "doctrine/inflector":"^2.0"

### ISSUE THREAD

**Issue by dsturm** [Log1x/acf-composer#14]
Hi Brandon,

using a new roots/sage install, composer installs `"doctrine/inflector":"2.0.1"`. Therefor the installation fails, since `stoutlogic/acf-builder` requires `"doctrine/inflector": "^1.1"`. Should this package require `"doctrine/inflector": "^1.4"` until `stoutlogic/acf-builder` is compatible with `"doctrine/inflector":"^2.0"`?

Best,
Daniel

**Comment by Log1x** [comment]
Yeah, let's do that for now. It looks like `doctrine/inflector` bumped the minimum PHP to `7.2` so I'm not sure if @stevep is going to jump at the idea or not.

Want to do a PR?

**Comment by stevep** [comment]
Yeah, I don't want to require 7.2 yet, because I know I have a lot of live projects that might not get upgraded and are just kind of just existing, and no one is paying me to upgrade them :) I'm sure others are probably in the same boat.

I quickly tried to drop in doctrine/inflector 2.0 to ACF builder and unfortunately they changed the namespace so it breaks the code. I was hoping to be able to support both via:

`"doctrine/inflector": "^1.1 || ^2.0",`

@Log1x do you know if there is a way around this? To rewrite the namespace in composer.json or something like that? Otherwise we might need to get creative to support both.

**Comment by Log1x** [comment]
At a glance it looks like `doctrine/instantiator` isn't actually being used on ACF Builder so that can get dropped.

Otherwise, it looks like our choices are slim outside of `class_exists()` or bumping ACF Builder a major version. Either way, `inflector` is only being used in 2 places to pluralize a string, so it shouldn't be too big of a deal to monkey patch otherwise.

**Comment by Log1x** [comment]
Closing this here. I'll probably push something to acf-builder at some point.

**Comment by Log1x** [comment]
https://github.com/StoutLogic/acf-builder/pull/120
