### ISSUE TITLE
❤️ feat req: Add support for vinkla/extended-acf

### ISSUE THREAD

**Issue by chrillep** [Log1x/acf-composer#167]
Would there be any benefit to swithing to extended-acf, since acf-builder does not seem to be maintained.

refs
* https://github.com/vinkla/extended-acf/issues/126#issuecomment-1573283799
* https://github.com/StoutLogic/acf-builder/issues/176

**Comment by Log1x** [comment]
I wouldn't switch because that'd involve a massive refactor for people wanting to upgrade, but I wouldn't be against supporting both. Extended looks really solid.

ACF Builder isn't as active as I wish it was but it also doesn't really need to be. By design, there's not much else to do to it right now.

**Comment by chrillep** [comment]
no, youre right. I just went for switching thinking it would be a bigger refactor. But as you pointed `vinkla/extended-acf` uses classes, so the instanceof approach seems maintainable. ill change the title description to "support vinkla/extended-acf"

**Comment by Log1x** [comment]
I've thought about this and while Extended ACF is great and I wish I would've known about it sooner, it simply does not fit with ACF Composer's current workflow and would be too much to maintain/document at the moment.
