### ISSUE TITLE
Localization of Block Name

### ISSUE THREAD

**Issue by cataras** [Log1x/acf-composer#261]
Hello,

I love using acf-composer to create my blocks. You've done a great job @Log1x!

There's still one thing I can't do. Is it possible to translate the name of a block? 

When I initialize my block like this: `'name' => __('Block name', 'sage'),`, the block refuses to be displayed.

Thanks for your help.

**Comment by Log1x** [comment]
Someone else would have to chime in for translations but ACF Composer doesn't officially support it (mainly when caching blocks) at the moment.

For what it's worth, you need to give your block a slug if you're going to translate the name because the name is otherwise used as the slug if none is provided – so that is probably why it is breaking in your case.

**Comment by cataras** [comment]
Exactly!

It works like this 👍: 
```
'slug' => 'block-name',
'name' => __('Block name', 'sage'),
```

 I would have thought of that anyway... 

Thanks a million!
